# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

    config.vm.define "haproxy-lb" do |node|
      node.vm.hostname = "haproxy-lb"
      node.vm.box = "generic/centos7"
      node.vm.network "private_network", ip: "192.168.100.30"
      node.vm.provider "virtualbox" do |vb|
        vb.name = "haproxy-lb"
        vb.cpus = 1
        vb.memory = 512
      end
    end
  
    (0..2).each do |i|
      config.vm.define "controller-#{i}" do |node|
        node.vm.hostname = "controller-#{i}"
        node.vm.box = "ubuntu/bionic64"
        node.vm.network "private_network", ip: "192.168.100.1#{i}"
        node.vm.provider "virtualbox" do |vb|
          vb.name = "controller-#{i}"
          vb.cpus = 1
          vb.memory = 1024
        end
      end
    end
    
    (0..2).each do |i|
      config.vm.define "worker-#{i}" do |node|
        node.vm.hostname = "worker-#{i}"
        node.vm.box = "ubuntu/bionic64"
        node.vm.network "private_network", ip: "192.168.100.2#{i}"
        node.vm.provider "virtualbox" do |vb|
          vb.name = "worker-#{i}"
          vb.cpus = 1
          vb.memory = 512
        end
      end
    end
    
  end
  